chore: modified loader functionality
msk4862/WhatUp pull request #8
Opened 2020-10-05 14:50 UTC by tusharmaharana

modified the loader functionality and added a button loader
#7

2020-10-05 15:07 UTC, tusharmaharana commented
![WhatUp](https://user-images.githubusercontent.com/47114550/95096922-811bf700-074a-11eb-85a3-40e3194e6c2a.gif)

2020-10-05 17:18 UTC, msk4862 requested changes

2020-10-06 05:12 UTC, tusharmaharana commented on frontend/src/components/Posts/Post.js
> +    const fetchData = async () => {
@msk4862 if I undo this the effect you're seeing in the gif won't be there

2020-10-06 05:15 UTC, tusharmaharana commented on frontend/src/components/Posts/Post.js
> +    const fetchData = async () => {
only the login button loader will be there but the loader in the PostShow will be the same as before
if you're okay with that then I will make the changes

2020-10-07 01:42 UTC, closed without merging